export {default as SidebarMain} from './Components/Common/Sidebar/Sidebar'
export {default as Navbar} from './Components/Common/Navbar/Navbar'
export {default as Breadcrumbs} from './Components/Common/Breadcrumb/Breadcrumbs'
export {default as HomePage} from './Components/Home/Home'
export {default as LoginPage} from './Components/Authentication/Login/Login'
export {default as CategoryPage} from './Components/Category/Category'
export {default as FoodPage} from './Components/Foods/Foods'
export {default as MenusPage} from './Components/Menus/Menus'